version: "3.4"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'store'
      MYSQL_USER: 'store'
      MYSQL_PASSWORD: 'store'
      MYSQL_ROOT_PASSWORD: 'store'
    ports:
      - '3306:3306'
